/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/creator-applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Creator Applications */
        get: operations["list_creator_applications_api_v1_admin_creator_applications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/creator-applications/{profile_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Creator Application */
        post: operations["approve_creator_application_api_v1_admin_creator_applications__profile_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/creator-applications/{profile_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Creator Application */
        post: operations["reject_creator_application_api_v1_admin_creator_applications__profile_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/disputes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Admin Disputes */
        get: operations["list_admin_disputes_api_v1_admin_disputes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/disputes/{dispute_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Admin Dispute */
        post: operations["resolve_admin_dispute_api_v1_admin_disputes__dispute_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Admin Overview */
        get: operations["get_admin_overview_api_v1_admin_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Bookings */
        get: operations["list_my_bookings_api_v1_bookings_get"];
        put?: never;
        /** Create Booking */
        post: operations["create_booking_api_v1_bookings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/incoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Incoming Bookings */
        get: operations["list_incoming_bookings_api_v1_bookings_incoming_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Booking */
        get: operations["get_booking_api_v1_bookings__booking_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Booking */
        post: operations["accept_booking_api_v1_bookings__booking_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Booking */
        post: operations["cancel_booking_api_v1_bookings__booking_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Booking */
        post: operations["complete_booking_api_v1_bookings__booking_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/conversation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Booking Conversation */
        get: operations["get_booking_conversation_api_v1_bookings__booking_id__conversation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/deliver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deliver Booking */
        post: operations["deliver_booking_api_v1_bookings__booking_id__deliver_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/deliverables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deliverables */
        get: operations["get_deliverables_api_v1_bookings__booking_id__deliverables_get"];
        put?: never;
        /** Post Deliverable */
        post: operations["post_deliverable_api_v1_bookings__booking_id__deliverables_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/dispute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Booking Dispute */
        get: operations["get_booking_dispute_api_v1_bookings__booking_id__dispute_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/disputes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open Booking Dispute */
        post: operations["open_booking_dispute_api_v1_bookings__booking_id__disputes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Payment */
        get: operations["get_payment_api_v1_bookings__booking_id__payments_get"];
        put?: never;
        /** Create Payment */
        post: operations["create_payment_api_v1_bookings__booking_id__payments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Booking */
        post: operations["reject_booking_api_v1_bookings__booking_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Booking Review */
        get: operations["get_booking_review_api_v1_bookings__booking_id__review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Booking Review */
        post: operations["create_booking_review_api_v1_bookings__booking_id__reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Booking */
        post: operations["start_booking_api_v1_bookings__booking_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Upload */
        post: operations["create_upload_api_v1_bookings__booking_id__uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Booking Workspace */
        get: operations["get_booking_workspace_api_v1_bookings__booking_id__workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/unread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Unread */
        get: operations["get_unread_api_v1_conversations_unread_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Messages */
        get: operations["get_messages_api_v1_conversations__conversation_id__messages_get"];
        put?: never;
        /** Post Message */
        post: operations["post_message_api_v1_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Read */
        post: operations["post_read_api_v1_conversations__conversation_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/creators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Creators */
        get: operations["list_creators_api_v1_creators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/creators/{creator_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Creator */
        get: operations["get_creator_api_v1_creators__creator_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/creators/{creator_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Creator Reviews */
        get: operations["list_creator_reviews_api_v1_creators__creator_id__reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deliverables/{deliverable_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Deliverable */
        delete: operations["delete_deliverable_api_v1_deliverables__deliverable_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dev/payments/{payment_id}/simulate-paid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate Paid */
        post: operations["simulate_paid_api_v1_dev_payments__payment_id__simulate_paid_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dev/payments/{payment_id}/simulate-release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate Release */
        post: operations["simulate_release_api_v1_dev_payments__payment_id__simulate_release_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/webhooks/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Payment Webhook */
        post: operations["payment_webhook_api_v1_payments_webhooks__provider__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_v1_profiles_me_patch"];
        trace?: never;
    };
    "/api/v1/profiles/me/creator": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert Creator */
        put: operations["upsert_creator_api_v1_profiles_me_creator_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/me/creator/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Creator */
        post: operations["submit_creator_api_v1_profiles_me_creator_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{upload_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Upload */
        post: operations["complete_upload_api_v1_uploads__upload_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{upload_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Download Upload */
        post: operations["download_upload_api_v1_uploads__upload_id__download_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminOverviewEnvelope */
        AdminOverviewEnvelope: {
            data: components["schemas"]["AdminOverviewOut"];
        };
        /** AdminOverviewOut */
        AdminOverviewOut: {
            /** Active Disputes */
            active_disputes: number;
            /** Pending Creator Applications */
            pending_creator_applications: number;
            /** Total Bookings */
            total_bookings: number;
            /** Total Creators */
            total_creators: number;
            /** Total Gmv Idr */
            total_gmv_idr: number;
            /** Total Users */
            total_users: number;
        };
        /** AttachmentOut */
        AttachmentOut: {
            /** Content Type */
            content_type: string;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** BookingCreatorOut */
        BookingCreatorOut: {
            /** City */
            city: string;
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Specialty */
            specialty: string;
        };
        /** BookingEnvelope */
        BookingEnvelope: {
            data: components["schemas"]["BookingOut"];
        };
        /** BookingListEnvelope */
        BookingListEnvelope: {
            /** Data */
            data: components["schemas"]["BookingOut"][];
        };
        /** BookingOut */
        BookingOut: {
            /** Client Name */
            client_name: string;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            creator: components["schemas"]["BookingCreatorOut"];
            /** Delivered At */
            delivered_at: string | null;
            /** Event City */
            event_city: string;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Notes */
            notes: string;
            /** Quoted Price Idr */
            quoted_price_idr: number;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
        };
        /** ConversationEnvelope */
        ConversationEnvelope: {
            data: components["schemas"]["ConversationOut"] | null;
        };
        /** ConversationOut */
        ConversationOut: {
            /**
             * Booking Id
             * Format: uuid
             */
            booking_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** CreateBookingRequest */
        CreateBookingRequest: {
            /**
             * Creator Id
             * Format: uuid
             */
            creator_id: string;
            /** Event City */
            event_city: string;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** CreateDisputeRequest */
        CreateDisputeRequest: {
            /** Description */
            description: string;
            /**
             * Reason Category
             * @enum {string}
             */
            reason_category: "not_delivered" | "quality_issue" | "unresponsive" | "other";
        };
        /** CreateMessageRequest */
        CreateMessageRequest: {
            /** Body */
            body?: string | null;
            /**
             * Client Message Id
             * Format: uuid
             */
            client_message_id: string;
            /**
             * Message Type
             * @enum {string}
             */
            message_type: "text" | "attachment";
            /** Upload Id */
            upload_id?: string | null;
        };
        /** CreateReviewRequest */
        CreateReviewRequest: {
            /** Comment */
            comment?: string | null;
            /** Rating */
            rating: number;
        };
        /** CreateUploadRequest */
        CreateUploadRequest: {
            /**
             * Content Type
             * @enum {string}
             */
            content_type: "image/jpeg" | "image/png" | "image/webp" | "application/pdf" | "application/zip";
            /** Filename */
            filename: string;
            /**
             * Purpose
             * @enum {string}
             */
            purpose: "chat_attachment" | "deliverable";
            /** Size Bytes */
            size_bytes: number;
        };
        /** CreatorApplicationListEnvelope */
        CreatorApplicationListEnvelope: {
            /** Data */
            data: components["schemas"]["CreatorApplicationOut"][];
        };
        /** CreatorApplicationOut */
        CreatorApplicationOut: {
            profile: components["schemas"]["CreatorProfileOut"];
            /** User Email */
            user_email: string;
            /** User Full Name */
            user_full_name: string;
        };
        /** CreatorDraftRequest */
        CreatorDraftRequest: {
            /**
             * Bio
             * @default
             */
            bio: string;
            /** City */
            city: string;
            /** Display Name */
            display_name: string;
            /** Specialty */
            specialty: string;
            /** Starting Price Idr */
            starting_price_idr: number;
        };
        /** CreatorListData */
        CreatorListData: {
            /** Items */
            items: components["schemas"]["CreatorPublicOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** CreatorListEnvelope */
        CreatorListEnvelope: {
            data: components["schemas"]["CreatorListData"];
        };
        /** CreatorProfileEnvelope */
        CreatorProfileEnvelope: {
            data: components["schemas"]["CreatorProfileOut"];
        };
        /** CreatorProfileOut */
        CreatorProfileOut: {
            /** Bio */
            bio: string;
            /** City */
            city: string;
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Rating Average
             * @default 0
             */
            rating_average: number;
            /**
             * Review Count
             * @default 0
             */
            review_count: number;
            /** Reviewed At */
            reviewed_at: string | null;
            /** Specialty */
            specialty: string;
            /** Starting Price Idr */
            starting_price_idr: number;
            /** Status */
            status: string;
            /** Submitted At */
            submitted_at: string | null;
        };
        /** CreatorPublicEnvelope */
        CreatorPublicEnvelope: {
            data: components["schemas"]["CreatorPublicOut"];
        };
        /** CreatorPublicOut */
        CreatorPublicOut: {
            /** Bio */
            bio: string;
            /** City */
            city: string;
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Rating Average
             * @default 0
             */
            rating_average: number;
            /**
             * Review Count
             * @default 0
             */
            review_count: number;
            /** Specialty */
            specialty: string;
            /** Starting Price Idr */
            starting_price_idr: number;
        };
        /** DeliverableEnvelope */
        DeliverableEnvelope: {
            data: components["schemas"]["DeliverableOut"];
        };
        /** DeliverableListEnvelope */
        DeliverableListEnvelope: {
            /** Data */
            data: components["schemas"]["DeliverableOut"][];
        };
        /** DeliverableOut */
        DeliverableOut: {
            /**
             * Booking Id
             * Format: uuid
             */
            booking_id: string;
            /** Content Type */
            content_type: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** Downloadable */
            downloadable: boolean;
            /** External Host */
            external_host: string | null;
            /** External Url */
            external_url: string | null;
            /** Filename */
            filename: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Media Type */
            media_type: string | null;
            /** Replaces Deliverable Id */
            replaces_deliverable_id: string | null;
            /** Size Bytes */
            size_bytes: number | null;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "private_file" | "external_link";
            /** Title */
            title: string;
            /** Upload Id */
            upload_id: string | null;
            /**
             * Uploaded By User Id
             * Format: uuid
             */
            uploaded_by_user_id: string;
        };
        /** DisputeEnvelope */
        DisputeEnvelope: {
            data: components["schemas"]["DisputeOut"] | null;
        };
        /** DisputeListEnvelope */
        DisputeListEnvelope: {
            /** Data */
            data: components["schemas"]["DisputeOut"][];
        };
        /** DisputeOut */
        DisputeOut: {
            /**
             * Booking Id
             * Format: uuid
             */
            booking_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Opened By Full Name */
            opened_by_full_name: string;
            /**
             * Opened By User Id
             * Format: uuid
             */
            opened_by_user_id: string;
            /** Reason Category */
            reason_category: string;
            /** Resolution Notes */
            resolution_notes: string | null;
            /** Resolved At */
            resolved_at: string | null;
            /** Resolved By Admin User Id */
            resolved_by_admin_user_id: string | null;
            /** Status */
            status: string;
        };
        /** ExternalDeliverableRequest */
        ExternalDeliverableRequest: {
            /** Description */
            description?: string | null;
            /**
             * External Url
             * Format: uri
             */
            external_url: string;
            /** Replaces Deliverable Id */
            replaces_deliverable_id?: string | null;
            /**
             * Source Type
             * @constant
             */
            source_type: "external_link";
            /** Title */
            title: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MessageOut */
        MessageOut: {
            attachment: components["schemas"]["AttachmentOut"] | null;
            /** Body */
            body: string | null;
            /**
             * Client Message Id
             * Format: uuid
             */
            client_message_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Message Type
             * @enum {string}
             */
            message_type: "text" | "attachment" | "system";
            /** Read At */
            read_at: string | null;
            sender: components["schemas"]["MessageSenderOut"];
        };
        /** MessagePageEnvelope */
        MessagePageEnvelope: {
            data: components["schemas"]["MessagePageOut"];
        };
        /** MessagePageOut */
        MessagePageOut: {
            /** Items */
            items: components["schemas"]["MessageOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** MessageSenderOut */
        MessageSenderOut: {
            /** Full Name */
            full_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** MockPaymentWebhookRequest */
        MockPaymentWebhookRequest: {
            /** Event Id */
            event_id: string;
            /** Event Type */
            event_type: string;
            /** Payment Id */
            payment_id: string;
        };
        /** PaymentEnvelope */
        PaymentEnvelope: {
            data: components["schemas"]["PaymentOut"];
        };
        /** PaymentOut */
        PaymentOut: {
            /** Amount Idr */
            amount_idr: number;
            /**
             * Booking Id
             * Format: uuid
             */
            booking_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Creator Net Idr */
            creator_net_idr: number;
            /** Held At */
            held_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Paid At */
            paid_at: string | null;
            /** Platform Fee Idr */
            platform_fee_idr: number;
            /** Provider */
            provider: string;
            /** Refunded At */
            refunded_at: string | null;
            /** Released At */
            released_at: string | null;
            /** Status */
            status: string;
        };
        /** PrivateDeliverableRequest */
        PrivateDeliverableRequest: {
            /** Description */
            description?: string | null;
            /** Replaces Deliverable Id */
            replaces_deliverable_id?: string | null;
            /**
             * Source Type
             * @constant
             */
            source_type: "private_file";
            /** Title */
            title: string;
            /**
             * Upload Id
             * Format: uuid
             */
            upload_id: string;
        };
        /** ReadReceiptEnvelope */
        ReadReceiptEnvelope: {
            data: components["schemas"]["ReadReceiptOut"];
        };
        /** ReadReceiptOut */
        ReadReceiptOut: {
            /** Count */
            count: number;
            /**
             * Read At
             * Format: date-time
             */
            read_at: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Password */
            password: string;
        };
        /** ResolveDisputeRequest */
        ResolveDisputeRequest: {
            /**
             * Resolution
             * @enum {string}
             */
            resolution: "resolved_client" | "resolved_creator";
            /** Resolution Notes */
            resolution_notes: string;
        };
        /** ReviewEnvelope */
        ReviewEnvelope: {
            data: components["schemas"]["ReviewOut"] | null;
        };
        /** ReviewOut */
        ReviewOut: {
            /**
             * Booking Id
             * Format: uuid
             */
            booking_id: string;
            /** Client Full Name */
            client_full_name: string;
            /**
             * Client User Id
             * Format: uuid
             */
            client_user_id: string;
            /** Comment */
            comment: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Creator Profile Id
             * Format: uuid
             */
            creator_profile_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Rating */
            rating: number;
        };
        /** ReviewPageEnvelope */
        ReviewPageEnvelope: {
            data: components["schemas"]["ReviewPageOut"];
        };
        /** ReviewPageOut */
        ReviewPageOut: {
            /** Items */
            items: components["schemas"]["ReviewOut"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Rating Average */
            rating_average: number;
            /** Review Count */
            review_count: number;
        };
        /** SignedUploadEnvelope */
        SignedUploadEnvelope: {
            data: components["schemas"]["SignedUploadOut"];
        };
        /** SignedUploadOut */
        SignedUploadOut: {
            /** Completed At */
            completed_at: string | null;
            /**
             * Content Type
             * @enum {string}
             */
            content_type: "image/jpeg" | "image/png" | "image/webp" | "application/pdf" | "application/zip";
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Purpose
             * @enum {string}
             */
            purpose: "chat_attachment" | "deliverable";
            /** Required Headers */
            required_headers: {
                [key: string]: string;
            };
            /** Size Bytes */
            size_bytes: number;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "completed" | "expired" | "rejected";
            /** Upload Url */
            upload_url: string;
        };
        /** SignedUrlEnvelope */
        SignedUrlEnvelope: {
            data: components["schemas"]["SignedUrlOut"];
        };
        /** SignedUrlOut */
        SignedUrlOut: {
            /** Url */
            url: string;
        };
        /** UnreadCountOut */
        UnreadCountOut: {
            /**
             * Booking Id
             * Format: uuid
             */
            booking_id: string;
            /** Count */
            count: number;
        };
        /** UnreadEnvelope */
        UnreadEnvelope: {
            /** Data */
            data: components["schemas"]["UnreadCountOut"][];
        };
        /** UpdateProfileRequest */
        UpdateProfileRequest: {
            /** Full Name */
            full_name: string;
        };
        /** UploadEnvelope */
        UploadEnvelope: {
            data: components["schemas"]["UploadOut"];
        };
        /** UploadOut */
        UploadOut: {
            /** Completed At */
            completed_at: string | null;
            /**
             * Content Type
             * @enum {string}
             */
            content_type: "image/jpeg" | "image/png" | "image/webp" | "application/pdf" | "application/zip";
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Purpose
             * @enum {string}
             */
            purpose: "chat_attachment" | "deliverable";
            /** Size Bytes */
            size_bytes: number;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "completed" | "expired" | "rejected";
        };
        /** UserEnvelope */
        UserEnvelope: {
            data: components["schemas"]["UserOut"];
        };
        /** UserOut */
        UserOut: {
            creator_profile?: components["schemas"]["CreatorProfileOut"] | null;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Admin */
            is_admin: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkspaceBookingOut */
        WorkspaceBookingOut: {
            /** Client Name */
            client_name: string;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            creator: components["schemas"]["BookingCreatorOut"];
            /** Delivered At */
            delivered_at: string | null;
            /** Event City */
            event_city: string;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Notes */
            notes: string;
            /** Quoted Price Idr */
            quoted_price_idr: number;
            /** Started At */
            started_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "requested" | "accepted" | "awaiting_payment" | "confirmed" | "in_progress" | "delivered" | "rejected" | "completed" | "cancelled";
        };
        /** WorkspaceEnvelope */
        WorkspaceEnvelope: {
            data: components["schemas"]["WorkspaceOut"];
        };
        /** WorkspaceOut */
        WorkspaceOut: {
            booking: components["schemas"]["WorkspaceBookingOut"];
            conversation: components["schemas"]["ConversationOut"] | null;
            /** Deliverables */
            deliverables: components["schemas"]["DeliverableOut"][];
            payment: components["schemas"]["WorkspacePaymentOut"] | null;
            /**
             * Role
             * @enum {string}
             */
            role: "client" | "creator";
            /** Unread Count */
            unread_count: number;
        };
        /** WorkspacePaymentOut */
        WorkspacePaymentOut: {
            /** Amount Idr */
            amount_idr: number;
            /** Creator Net Idr */
            creator_net_idr: number;
            /** Held At */
            held_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Paid At */
            paid_at: string | null;
            /** Platform Fee Idr */
            platform_fee_idr: number;
            /** Refunded At */
            refunded_at: string | null;
            /** Released At */
            released_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "paid" | "held" | "released" | "refunded" | "failed" | "expired";
        };
        /** MessageEnvelope */
        app__api__schemas__MessageEnvelope: {
            /** Data */
            data: {
                [key: string]: string;
            };
        };
        /** MessageEnvelope */
        app__api__workspace_schemas__MessageEnvelope: {
            data: components["schemas"]["MessageOut"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_creator_applications_api_v1_admin_creator_applications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatorApplicationListEnvelope"];
                };
            };
        };
    };
    approve_creator_application_api_v1_admin_creator_applications__profile_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatorProfileEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_creator_application_api_v1_admin_creator_applications__profile_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatorProfileEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_admin_disputes_api_v1_admin_disputes_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisputeListEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_admin_dispute_api_v1_admin_disputes__dispute_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dispute_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveDisputeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisputeEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_admin_overview_api_v1_admin_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOverviewEnvelope"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__api__schemas__MessageEnvelope"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_bookings_api_v1_bookings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingListEnvelope"];
                };
            };
        };
    };
    create_booking_api_v1_bookings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_incoming_bookings_api_v1_bookings_incoming_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingListEnvelope"];
                };
            };
        };
    };
    get_booking_api_v1_bookings__booking_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_booking_api_v1_bookings__booking_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_booking_api_v1_bookings__booking_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_booking_api_v1_bookings__booking_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_booking_conversation_api_v1_bookings__booking_id__conversation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deliver_booking_api_v1_bookings__booking_id__deliver_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deliverables_api_v1_bookings__booking_id__deliverables_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliverableListEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_deliverable_api_v1_bookings__booking_id__deliverables_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrivateDeliverableRequest"] | components["schemas"]["ExternalDeliverableRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliverableEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_booking_dispute_api_v1_bookings__booking_id__dispute_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisputeEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_booking_dispute_api_v1_bookings__booking_id__disputes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDisputeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisputeEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_payment_api_v1_bookings__booking_id__payments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_payment_api_v1_bookings__booking_id__payments_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_booking_api_v1_bookings__booking_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_booking_review_api_v1_bookings__booking_id__review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_booking_review_api_v1_bookings__booking_id__reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_booking_api_v1_bookings__booking_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_upload_api_v1_bookings__booking_id__uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignedUploadEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_booking_workspace_api_v1_bookings__booking_id__workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_unread_api_v1_conversations_unread_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreadEnvelope"];
                };
            };
        };
    };
    get_messages_api_v1_conversations__conversation_id__messages_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePageEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_message_api_v1_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__api__workspace_schemas__MessageEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_read_api_v1_conversations__conversation_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadReceiptEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_creators_api_v1_creators_get: {
        parameters: {
            query?: {
                q?: string | null;
                city?: string | null;
                specialty?: string | null;
                min_price?: number | null;
                max_price?: number | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatorListEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_creator_api_v1_creators__creator_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                creator_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatorPublicEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_creator_reviews_api_v1_creators__creator_id__reviews_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                creator_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewPageEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_deliverable_api_v1_deliverables__deliverable_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deliverable_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_paid_api_v1_dev_payments__payment_id__simulate_paid_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                payment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_release_api_v1_dev_payments__payment_id__simulate_release_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                payment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    payment_webhook_api_v1_payments_webhooks__provider__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MockPaymentWebhookRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_me_api_v1_profiles_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_creator_api_v1_profiles_me_creator_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatorDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatorProfileEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_creator_api_v1_profiles_me_creator_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatorProfileEnvelope"];
                };
            };
        };
    };
    complete_upload_api_v1_uploads__upload_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_upload_api_v1_uploads__upload_id__download_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignedUrlEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
